# Copyright (C) 2022-2026 CharlesWithC All rights reserved.
# Author: @CharlesWithC

import os

import argparse
import uvicorn

import src.bannergen.api as api
from src.bannergen.app import app

app.add_api_route(path="/banner", endpoint=api.get_banner, methods=["POST"])

drivershub = """    ____       _                         __  __      __
   / __ \\_____(_)   _____  __________   / / / /_  __/ /_
  / / / / ___/ / | / / _ \\/ ___/ ___/  / /_/ / / / / __ \\
 / /_/ / /  / /| |/ /  __/ /  (__  )  / __  / /_/ / /_/ /
/_____/_/  /_/ |___/\\___/_/  /____/  /_/ /_/\\__,_/_.___/
                                                         """

description = '''Drivers Hub: Banner Generator

An extension of the Drivers Hub server, specifically used for generating member banners.

Read /docs/bannergen.md for more information on this design.
'''

parser = argparse.ArgumentParser(prog='main', description=description, formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument("--host", help = "server host (default 127.0.0.1)", default = "127.0.0.1")
parser.add_argument("--port", help = "server port (default 8700)", type=int, default = 8700)
parser.add_argument("--workers", help = "server workers (default 2)", type=int, default = 2)
parser.add_argument("--enable-performance-header", help = "add headers with performance information", action='store_true')
parser.add_argument("--memory-threshold", help = "limit memory usage; block new requests when the threshold is reached (in MB, default 0/disabled)", type=int, default=0)
args, _ = parser.parse_known_args() # unknown args generated by uvicorn

app.enable_performance_header = "enable_performance_header" in args.__dict__.keys() and args.enable_performance_header
app.memory_threshold = args.memory_threshold if "memory_threshold" in args.__dict__.keys() else 0

if __name__ == "__main__":
    print(drivershub)
    print("Drivers Hub: Banner Generator")
    print("Copyright (C) 2022-2026 CharlesWithC All rights reserved.")
    print("")

    if not os.path.exists("/tmp/hub"):
        os.mkdir("/tmp/hub")
    if not os.path.exists("/tmp/hub/banner"):
        os.mkdir("/tmp/hub/banner")
    if not os.path.exists("/tmp/hub/logo"):
        os.mkdir("/tmp/hub/logo")
    if not os.path.exists("/tmp/hub/template"):
        os.mkdir("/tmp/hub/template")
    if not os.path.exists("/tmp/hub/avatar"):
        os.mkdir("/tmp/hub/avatar")
    uvicorn.run("src.bannergen.app:app", host=args.host, port=args.port, workers=args.workers, log_level="info", timeout_keep_alive=15)
