#!/usr/bin/python3

# Copyright (C) 2022-2026 CharlesWithC All rights reserved.
# Author: @CharlesWithC

import argparse
import json
import os

import uvicorn

import src.multilang as ml
from src.app import createApp
from src.config import validateConfig
from src.functions.dataop import b64e
from src.logger import logger

drivershub = """    ____       _                         __  __      __
   / __ \\_____(_)   _____  __________   / / / /_  __/ /_
  / / / / ___/ / | / / _ \\/ ___/ ___/  / /_/ / / / / __ \\
 / /_/ / /  / /| |/ /  __/ /  (__  )  / __  / /_/ / /_/ /
/_____/_/  /_/ |___/\\___/_/  /____/  /_/ /_/\\__,_/_.___/
                                                         """

description = '''Drivers Hub: Backend

To start the Drivers Hub server, provide one or more configuration files with --config, --configs, or --config-directory argument. At least one configuration file must be provided.

When using multiple Drivers Hubs, --master-host, --master-port, --master-workers must be provided, and per-drivers-hub configuration on host, port, workers would be ignored.

Use --banner-service-url to change the URL of banner service, in the case of a port conflict or offloaded service.

Use --use-master-db-pool and relevant environment variables to enable master database pool. When master database pool is enabled, all Drivers Hubs will share a single database connection pool, and per-drivers-hub database configuration except database name will be ignored.

Environemnt variables for master-db: MASTER_DB_HOST, MASTER_DB_USER, MASTER_DB_PASSWORD, MASTER_DB_POOLSIZE

Use './drivershub setup init-db' to initialize database on first run.

Use './drivershub setup {create-user,accept-user,update-roles}' for quick user setup. See README.md for more information.'''

parser = argparse.ArgumentParser(prog='drivershub', description=description, formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument("--config", help = "path to single config file")
parser.add_argument("--configs", help = "path to multiple config files", nargs="*")
parser.add_argument("--config-directory", help = "path to a directory containing multiple config files")
parser.add_argument("--master-host", help = "master server host")
parser.add_argument("--master-port", help = "master server port", type=int)
parser.add_argument("--master-workers", help = "master server workers", type=int)
parser.add_argument("--banner-service-url", help = "url of the banner service (default http://127.0.0.1:8700/banner)", default="http://127.0.0.1:8700/banner")
parser.add_argument("--use-master-db-pool", help = "enable master database pool (provide credentials with environment variables)", action='store_true')
parser.add_argument("--enable-master-openapi", help = "enable master swagger ui for api documentation", action='store_true')
parser.add_argument("--master-openapi-path", help = "master swagger ui route (default /)")
parser.add_argument("--ignore-external-plugins", help = "ignore external plugins", action='store_true')
parser.add_argument("--rebuild-dlog-stats", help = "rebuild dlog stats table based on raw data (use when inconsistent data is present)", action='store_true')
parser.add_argument("--enable-performance-header", help = "add headers with performance information", action='store_true')
parser.add_argument("--disable-upgrader", help = "prevent the upgrader from running", action='store_true')
parser.add_argument("--force-upgrade-from", help = "force upgrader to upgrade from a specific version (2_x_x)")
parser.add_argument("--memory-threshold", help = "limit memory usage; block new requests when the threshold is reached (in MB, default 0/disabled)", type=int, default=0)
args, _ = parser.parse_known_args() # unknown args generated by uvicorn

subparsers = parser.add_subparsers(dest = 'command')
parser_setup = subparsers.add_parser('setup', description = 'Setup Drivers Hub')
subparsers_setup = parser_setup.add_subparsers(dest = 'subcommand')

parser_init_db = subparsers_setup.add_parser('init-db', description = 'initialize database')

parser_create_user = subparsers_setup.add_parser('create-user', description = 'create a new user')
parser_create_user.add_argument('email', type = str, help = "user email")

parser_create_user = subparsers_setup.add_parser('accept-user', description = 'accept a user as member')
parser_create_user.add_argument('uid', type = int, help = "uid (for users; not userid)")

parser_update_roles = subparsers_setup.add_parser('update-roles', description = 'Overwrite roles of an existing user')
parser_update_roles.add_argument('userid', type = int, help = "user id (for members; not uid)")
parser_update_roles.add_argument('roles', nargs = '+', type = int, help = "list of roles (separate by space)")

args = parser.parse_args()

config_paths = None
if args.config is not None:
    config_paths = [args.config]
elif args.configs is not None:
    config_paths = args.configs
elif args.config_directory is not None:
    if not os.path.exists(args.config_directory):
        logger.error("Invalid config-directory, quitted.")
        os._exit(42)
    config_files = sorted(os.listdir(args.config_directory))
    config_paths = [os.path.join(args.config_directory, x) for x in config_files if x.endswith(".json")]

if args.command == "setup":
    import src.setup as setup
    from src.config import validateConfig
    from src.functions import Dict2Obj

    if not config_paths:
        logger.error("No config is provided, quitted.")
        os._exit(42)

    if len(config_paths) > 1:
        logger.error("Only one config file is allowed in setup mode, quitted.")
        os._exit(42)

    config = json.loads(open(config_paths[0], "r", encoding="utf-8").read())
    config = validateConfig(config)
    config = Dict2Obj(config)

    setup.handle_commands(config, args)
    os._exit(0)

openapi_path = ""
if args.enable_master_openapi is True:
    if args.master_openapi_path is not None:
        openapi_path = args.master_openapi_path
        if not openapi_path.startswith("/"):
            openapi_path = "/" + openapi_path
    else:
        openapi_path = "/"

if config_paths is not None:
    os.environ["LAUNCH_ARGS"] = b64e(json.dumps(args.__dict__))
    os.environ["CONFIG_PATHS"] = b64e(json.dumps(config_paths))
    os.environ["OPENAPI_PATH"] = openapi_path

if args.use_master_db_pool is True:
    if not all([os.environ.get("MASTER_DB_HOST"), os.environ.get("MASTER_DB_USER"), os.environ.get("MASTER_DB_PASSWORD"), os.environ.get("MASTER_DB_POOLSIZE")]):
        logger.error("Environment variables 'MASTER_DB_HOST', 'MASTER_DB_USER, 'MASTER_DB_PASSWORD', 'MASTER_DB_POOLSIZE' must be provided when using master database pool, quited.")
        os._exit(42)
    if int(os.environ["MASTER_DB_POOLSIZE"]) < 5:
        logger.error("Master database connection pool size must be at least 5, quited.")
        os._exit(42)

if __name__ == "__main__":
    from src.static import version
    for line in drivershub.split("\n"):
        logger.info(line)
    logger.info(f"Drivers Hub: Backend (v{version})")
    logger.info("Copyright (C) 2022-2026 CharlesWithC All rights reserved.")
    logger.info(f"Languages: {', '.join(ml.LANGUAGES)}")
    logger.info("")

    # validate config here
    # this ensures routing will always be able to load all configs
    # uvicorn would load routing dynamically, which would create the full app
    for config_path in config_paths:
        dh = createApp(config_path, multi_mode = False, dry_run = True, args = args.__dict__, master_db = None)
        if not dh:
            os._exit(42)

    if len(config_paths) == 1:
        try:
            config_txt = open(config_paths[0], "r", encoding="utf-8").read()
            config_json = json.loads(config_txt)
            config_dict = validateConfig(config_json)

            host = config_dict["server_host"]
            port = config_dict["server_port"]
            workers = config_dict["server_workers"]
        except:
            logger.warning("No valid config is loaded, quited.")
            os._exit(42)

    # for single hub, master config can override hub config
    # if master config is not provided, then use hub config
    if args.master_host and args.master_port:
        host = args.master_host
        port = args.master_port
    if args.master_workers:
        workers = args.master_workers

    if host is None and port is None:
        logger.error("--master-host and --master-port must be provided when starting multiple Drivers Hubs within one server process, quited.")
        os._exit(42)

    uvicorn.run("src.routing:createFullApp", factory=True, host=host, port=port, log_level="info", access_log=False, proxy_headers=True, workers=workers, timeout_worker_healthcheck=120)
